# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78fa80a0b0e440146bbd55ef40254fcdbaed848281d43d61704de92c52bf3ac4986e72228558fdaa2554ab4fba40da388b5819a44c2d069d41ff3369a6adfc8d

test:
  secret_key_base: 0006a709acdbb967f0bc1bee0fd180371d31f3f1232458da31752af071f8e5f99535eab0e881aa1004b2a67a82bf219f637461fe8339c3dad5ed4e56680b3ae0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
